ccflags-y := -I$(src)/../include
EXTRA_CFLAGS += -DDEBUG

obj-m += frags.o

frags-objs += nf_hook.o
frags-objs += config.o
frags-objs += receiver.o
frags-objs += skb_ops.o
frags-objs += ipv6_hdr_iterator.o
frags-objs += send_packet.o
