#ifndef _JOOL_MOD_STATS_H
#define _JOOL_MOD_STATS_H

/**
 * @file
 * A wrapper for the kernel's stat functions.
 *
 * This exists because, based on experience, we can't really afford the assumptions that led to
 * those functions lacking argument validations.
 */

#include "nat64/mod/common/packet.h"

enum jool_stat {
	JSTAT_NONE,
	JSTAT_SUCCESS,

	JSTAT_ENOMEM,

	JSTAT_XLATOR_DISABLED,

	JSTAT_SKB_SHARED,
	JSTAT_L3HDR_OFFSET,
	JSTAT_SKB_TRUNCATED,
	JSTAT_FRAGMENTED_PING,
	JSTAT_HDR6,
	JSTAT_HDR4,

	JSTAT_UNKNOWN_L3_PROTO,
	JSTAT_UNKNOWN_L4_PROTO,
	JSTAT_UNKNOWN_ICMP6_TYPE,
	JSTAT_UNKNOWN_ICMP4_TYPE,
	JSTAT_DOUBLE_ICMP6_ERROR,
	JSTAT_DOUBLE_ICMP4_ERROR,
	JSTAT_UNKNOWN_PROTO_INNER,

	JSTAT_HAIRPIN_LOOP,
	JSTAT_POOL6_MISMATCH,
	JSTAT_POOL4_MISMATCH,
	JSTAT_ICMP6_FILTER,
	JSTAT_UNTRANSLATABLE_DST6,
	JSTAT_UNTRANSLATABLE_DST4,
	JSTAT_MASK_DOMAIN_NOT_FOUND,
	JSTAT_BIB6_NOT_FOUND,
	JSTAT_BIB4_NOT_FOUND,
	JSTAT_BIB_NOT_FOUND,
	JSTAT_ADF,
	JSTAT_V4_SYN,
	JSTATS_SO_EXISTS,
	JSTAT_SYN6_EXPECTED,
	JSTAT_SYN4_EXPECTED,

	JSTAT_TYPE1PKT,
	JSTAT_TYPE2PKT,
	JSTAT_SO_EXISTS,
	JSTAT_SO_FULL,

	JSTAT64_SRC,
	JSTAT64_DST,
	JSTAT64_PSKB_COPY,
	JSTAT64_ICMP_CSUM,
	JSTAT64_ICMP_TYPE,
	JSTAT64_PKT_TOO_BIG,
	JSTAT64_UNTRANSLATABLE_DEST_UNREACH,
	JSTAT64_UNTRANSLATABLE_PARAM_PROB,
	JSTAT64_UNTRANSLATABLE_PARAM_PROB_PTR,
	JSTAT64_TTL,
	JSTAT64_SEGMENTS_LEFT,

	JSTAT46_SRC,
	JSTAT46_DST,
	JSTAT46_PSKB_COPY,
	JSTAT46_ICMP_CSUM,
	JSTAT46_ICMP_TYPE,
	JSTAT46_ICMP_PTR,
	JSTAT46_UNTRANSLATABLE_DEST_UNREACH,
	JSTAT46_UNTRANSLATABLE_PARAM_PROB,
	JSTAT46_TTL,
	JSTAT46_SRC_ROUTE,
	JSTAT46_FRAGMENTED_ZERO_CSUM,

	JSTAT_FAILED_ROUTES,
	JSTAT_PKT_TOO_BIG,
	JSTAT_DST_OUTPUT,

	JSTAT_ICMP6ERR_SUCCESS,
	JSTAT_ICMP6ERR_FAILURE,
	JSTAT_ICMP4ERR_SUCCESS,
	JSTAT_ICMP4ERR_FAILURE,

	/* "WTF was that" errors only. */
	JSTAT_UNKNOWN,
};

struct jool_stats;

struct jool_stats *jstat_alloc(void);
void jstat_get(struct jool_stats *stats);
void jstat_put(struct jool_stats *stats);

void jstat_inc(struct jool_stats *stats, int field);

#endif /* _JOOL_MOD_STATS_H */
