#ifndef NAT64_INCLUDE_NAT64_COMMON_JOOLD_JOOLD_CONFIG_H_
#define NAT64_INCLUDE_NAT64_COMMON_JOOLD_JOOLD_CONFIG_H_

/* This has to be <= 32. */
#define JOOLD_MULTICAST_GROUP 30
#define JOOLD_NETLINK_FAMILY
/* TODO where did this number come from? */
#define JOOLD_MAX_PAYLOAD 2048
#define JOOLD_MAX_SESSIONS (JOOLD_MAX_PAYLOAD / sizeof(struct joold_session))

#endif /* NAT64_INCLUDE_NAT64_COMMON_JOOLD_JOOLD_CONFIG_H_ */
