#CC=cgcc
ccflags-y := -I$(src)/../../include

#EXTRA_CFLAGS += -DDEBUG
# Note: if you want to activate the benchmark feature, you need to activate the following flag, and
#	the "log_time.o" object, also you need to activate in the usr-app (usr/src/Makefile.am)
#EXTRA_CFLAGS += -DBENCHMARK
EXTRA_CFLAGS += -DSTATEFUL

obj-m += jool-stateful.o

jool-common += ../common/rfc6145/4to6.o
jool-common += ../common/rfc6145/6to4.o
jool-common += ../common/rfc6145/common.o
jool-common += ../common/rfc6145/core.o
jool-common += ../common/types.o
jool-common += ../common/str_utils.o
jool-common += ../common/packet.o
jool-common += ../common/stats.o
#jool-common += ../common/log_time.o
jool-common += ../common/icmp_wrapper.o
jool-common += ../common/ipv6_hdr_iterator.o
jool-common += ../common/rfc6052.o
jool-common += ../common/nl_buffer.o
jool-common += ../common/random.o
jool-common += ../common/rbtree.o
jool-common += ../common/config.o
jool-common += ../common/nl_handler.o
jool-common += ../common/route.o
jool-common += ../common/send_packet.o
jool-common += ../common/core.o

jool-stateful += pkt_queue.o
jool-stateful += poolnum.o
jool-stateful += pool6.o
jool-stateful += pool4.o
jool-stateful += host6_node.o
jool-stateful += bib_db.o
jool-stateful += session_db.o
jool-stateful += static_routes.o
jool-stateful += fragment_db.o
jool-stateful += determine_incoming_tuple.o
jool-stateful += filtering_and_updating.o
jool-stateful += compute_outgoing_tuple.o
jool-stateful += handling_hairpinning.o
jool-stateful += nf_hook.o

jool-stateful-objs += ${jool-common} ${jool-stateful}
