#CC=cgcc
ccflags-y := -I$(src)/../../include

#EXTRA_CFLAGS += -DDEBUG
# Note: if you want to activate the benchmark feature, you need to activate the following flag, and
#	the "log_time.o" object, also you need to activate in the usr-app (usr/src/Makefile.am)
#EXTRA_CFLAGS += -DBENCHMARK
EXTRA_CFLAGS += -DSTATEFUL

obj-m += jool_stateful.o

jool_common += ../common/rfc6145/4to6.o
jool_common += ../common/rfc6145/6to4.o
jool_common += ../common/rfc6145/common.o
jool_common += ../common/rfc6145/core.o
jool_common += ../common/types.o
jool_common += ../common/str_utils.o
jool_common += ../common/packet.o
jool_common += ../common/stats.o
#jool_common += ../common/log_time.o
jool_common += ../common/icmp_wrapper.o
jool_common += ../common/ipv6_hdr_iterator.o
jool_common += ../common/rfc6052.o
jool_common += ../common/nl_buffer.o
jool_common += ../common/random.o
jool_common += ../common/rbtree.o
jool_common += ../common/config.o
jool_common += ../common/nl_handler.o
jool_common += ../common/route.o
jool_common += ../common/send_packet.o
jool_common += ../common/core.o

jool_stateful += pkt_queue.o
jool_stateful += poolnum.o
jool_stateful += pool6.o
jool_stateful += pool4.o
jool_stateful += host6_node.o
jool_stateful += bib_db.o
jool_stateful += session_db.o
jool_stateful += static_routes.o
jool_stateful += fragment_db.o
jool_stateful += determine_incoming_tuple.o
jool_stateful += filtering_and_updating.o
jool_stateful += compute_outgoing_tuple.o
jool_stateful += handling_hairpinning.o
jool_stateful += nf_hook.o

jool_stateful-objs += ${jool_common} ${jool_stateful}
