#ifndef _JOOL_USR_ARGP_OPTIONS_H
#define _JOOL_USR_ARGP_OPTIONS_H

#include <argp.h>
#include "common/config.h"

#define BOOL_FORMAT "BOOL"
#define NUM_FORMAT "NUM"
#define NUM_ARRAY_FORMAT "NUM[,NUM]*"
#define TRANSPORT6_FORMAT "ADDR6#NUM"
#define TRANSPORT4_FORMAT "ADDR4#NUM"
#define PREFIX6_FORMAT "ADDR6/NUM"
#define PREFIX4_FORMAT "ADDR4/NUM"
#define OPTIONAL_PREFIX6_FORMAT "(ADDR6/NUM|null)"
#define STRING_FORMAT "STRING"

/**
 * The flags the user can write as program parameters.
 */
enum argp_flags {
	ARGP_INAME = 4000,

	/* Modes */
	ARGP_INSTANCE = 7001,
	ARGP_POOL4 = '4',
	ARGP_BIB = 'b',
	ARGP_SESSION = 's',
	ARGP_JOOLD = 7002,
	ARGP_EAMT = 'e',
	ARGP_BLACKLIST = 7000,
	ARGP_RFC6791 = 6791,
	ARGP_GLOBAL = 'g',
	ARGP_PARSE_FILE = 'p',

	/* Operations */
	ARGP_DISPLAY = 'd',
	ARGP_COUNT = 'c',
	ARGP_ADD = 'a',
	ARGP_UPDATE = 5000,
	ARGP_REMOVE = 'r',
	ARGP_FLUSH = 'f',
	ARGP_ADVERTISE = 5002,
	ARGP_TEST = 5001,

	/* Instance */
	ARGP_NETFILTER = 8000,
	ARGP_IPTABLES = 8001,

	/* Pools */
	ARGP_QUICK = 'q',
	ARGP_MARK = 'm',
	ARGP_MAX_ITERATIONS = 3003,
	ARGP_FORCE = 3002,

	/* BIB, session */
	ARGP_TCP = 't',
	ARGP_UDP = 'u',
	ARGP_ICMP = 'i',
	ARGP_NUMERIC_HOSTNAME = 'n',
	ARGP_CSV = 2022,
	ARGP_NO_HEADERS = 2023,

	/* Global */
	ARGP_ENABLE_TRANSLATION = GT_ENABLE,
	ARGP_DISABLE_TRANSLATION = GT_DISABLE,
	ARGP_MANUAL_ENABLE = GT_ENABLE_BOOL,
	ARGP_RESET_TCLASS = GT_RESET_TCLASS,
	ARGP_RESET_TOS = GT_RESET_TOS,
	ARGP_NEW_TOS = GT_NEW_TOS,
	ARGP_PLATEAUS = GT_MTU_PLATEAUS,
	ARGP_POOL6 = GT_POOL6,
	ARGP_COMPUTE_CSUM_ZERO = GT_COMPUTE_UDP_CSUM_ZERO,
	ARGP_RANDOMIZE_RFC6791 = GT_RANDOMIZE_RFC6791,
	ARGP_EAM_HAIRPIN_MODE = GT_EAM_HAIRPINNING_MODE,
	ARGP_DROP_ADDR = GT_DROP_BY_ADDR,
	ARGP_DROP_INFO = GT_DROP_ICMP6_INFO,
	ARGP_DROP_TCP = GT_DROP_EXTERNAL_TCP,
	ARGP_SRC_ICMP6ERRS_BETTER = GT_SRC_ICMP6ERRS_BETTER,
	ARGP_F_ARGS = GT_F_ARGS,
	ARGP_HANDLE_RST_DURING_FIN_RCV = GT_HANDLE_RST_DURING_FIN_RCV,
	ARGP_UDP_TO = GT_UDP_TIMEOUT,
	ARGP_ICMP_TO = GT_ICMP_TIMEOUT,
	ARGP_TCP_TO = GT_TCP_EST_TIMEOUT,
	ARGP_TCP_TRANS_TO = GT_TCP_TRANS_TIMEOUT,
	ARGP_BIB_LOGGING = GT_BIB_LOGGING,
	ARGP_SESSION_LOGGING = GT_SESSION_LOGGING,
	ARGP_STORED_PKTS = GT_MAX_PKTS,
	ARGP_SS_ENABLED = GT_SS_ENABLED,
	ARGP_SS_FLUSH_ASAP = GT_SS_FLUSH_ASAP,
	ARGP_SS_FLUSH_DEADLINE = GT_SS_FLUSH_DEADLINE,
	ARGP_SS_CAPACITY = GT_SS_CAPACITY,
	ARGP_SS_MAX_PAYLOAD = GT_SS_MAX_PAYLOAD,
	ARGP_RFC6791V6_PREFIX = GT_RFC6791V6_PREFIX,
};

struct argp_option *build_opts(void);
struct argp_option *get_global_opts(void);

#endif /* _JOOL_USR_ARGP_OPTIONS_H */
