#!/bin/bash

# test-frags 4-udp-csumok-nodf 6-udp-csumok-nodf
# test-frags 4-udp-csumfail-nodf 6-udp-csumfail-nodf

#./test-single.sh manual/igmp6-sender manual/igmp6-receiver
# 7 is hop limit.
# I don't know why it's 0xff the first time the test is run,
# and 0x40 afterwards.
# It doesn't seem to matter, though. But maybe I should look more into it.
# Notice this field is generated by the kernel (icmp6_send()), not by Jool.
./test-single.sh manual/igmp4-sender manual/igmp4-receiver 1,4,5,7,10,11

graybox stats display
graybox stats flush

