.\" Manpage for jool's userspace app.
.\" Report bugs to jool@nic.mx.

.TH jool 8 2017-07-25 v3.5.4 "NAT64 Jool's Userspace Application"

.SH NAME
jool - Interact with NAT64 Jool (the kernel module).

.SH DESCRIPTION
Sends commands and requests to NAT64 Jool.
.br
NAT64 Jool is a kernel module you load into a Linux kernel. It implements RFC 6146.

.SH AVAILABILITY
Linux is the only OS in which this program makes sense.
.br
Kernels 3.2.0 and up.

.SH SYNTAX
jool_siit --instance (
.br
	[--add]
.br
	| --remove
.br
)
.P
jool --pool6 (
.br
	[--display] [--csv]
.br
	| --count
.br
.RI "	| --add " <IPv6-prefix> " [--force]"
.br
.RI "	| --remove " <IPv6-prefix>
.br
.RI "	| --flush"
.br
)
.P
jool --pool4 (
.br
	[--display] [--csv]
.br
	| --count
.br
.RI "	| --add [" <PROTOCOLS> "] " "<IPv4-prefix> <port-range>" " [--mark " <mark> "] [--force]"
.br
.RI "	| --remove [" <PROTOCOLS> "] " "<IPv4-prefix> <port-range>" " [--mark " <mark> "] [--quick]"
.br
	| --flush [--quick]
.br
)
.P
.RI "jool --bib [" <PROTOCOLS> "] (
.br
	[--display] [--numeric] [--csv]
.br
	| --count
.br
.RI "	| --add " "<IPv4-transport-address> <IPv6-transport-address>"
.br
.RI "	| --remove " "<IPv4-transport-address> <IPv6-transport-address>"
.br
)
.P
.RI "jool --session [" <PROTOCOLS> "] (
.br
	[--display] [--numeric] [--csv]
.br
	| --count
.br
)
.P
.RI "jool [--global] (
.br
	[--display]
.br
.RI "	| [--update] " FLAG_KEY = FLAG_VALUE
.br
)
.P
.RI "jool [--file] (
.br
	/path/to/json/file
.br
)


.SH OPTIONS
.SS Operations
.IP --display
Print the table as output.
.IP --count
Count and print the number of entries in the table.
.IP --add
Create a new row using the rest of the arguments.
.IP --update
Change a configuration value based on the rest of the arguments.
.IP --remove
Delete the row described by the rest of the arguments.
.IP --flush
Empty the table.

.SS <PROTOCOLS>
They are not mutually exclusive. If you provide no protocol, the default is all protocols. If you provide at least one protocol, the rest will be turned off.
.IP --udp
Apply the operation on the UDP table.
.IP --tcp
Apply the operation on the TCP table.
.IP --icmp
Apply the operation on the ICMP table.

.SS Others
.IP <IPv6-prefix>
.RI "IPv6 prefix to add to or remove from Jool's IPv6 pool.
.br
.RI "The format is " IPV6_ADDRESS "[/" PREFIX_LENGTH "]."
.br
.RI "PREFIX_LENGTH defaults to 128."
.br
Exampĺe: 64:ff9b::/96
.IP <IPv4-prefix>
.RI "IPv4 addresses to add to or remove from Jool's IPv4 pool."
.br
.RI "The format is " IPV4_ADDRESS "[/" PREFIX_LENGTH "]."
.br
.RI "PREFIX_LENGTH defaults to 32."
.br
Exampĺe: 1.2.3.4/30 (Means 1.2.3.4, 1.2.3.5, 1.2.3.6 and 1.2.3.7)
.IP <port-range>
.RI "Range of ports (or ICMP ids) of the " <IPv4-prefix> " addresses which are being added or removed from Jool's IPv4 pool."
.br
.RI "The format is " LOWER "[-" UPPER "]."
.br
.RI "If you omit the upper port, you're only inserting port " LOWER "."
.br
If you omit this argument entirely, Jool will insert or remove all existing ports/ids.
.br
Exampĺe: 61001-65535
.IP <IPv4-transport-address>
.RI "IPv4 field of the BIB entry being added or removed.
.br
.RI "The format is " IPV4_ADDRESS # PORT "."
.br
Exampĺe: 10.20.30.40#5000
.IP <IPv6-transport-address>
.RI "IPv6 field of the BIB entry being added or removed.
.br
.RI "The format is " IPV6_ADDRESS # PORT "."
.br
Exampĺe: 1::2#5000
.IP --quick
Do not remove orphaned BIB and session entries.
.IP --numeric
Do not try to resolve hostnames.
.IP --csv
Output the table in Comma/Character-Separated Values (.csv) format.

.SS "--global's FLAG_KEYs"
.IP --disable
Pause translation of packets.
.IP --enable
Resume translation of packets.
.IP --zeroize-traffic-class=BOOL
Always set the IPv6 header's 'Traffic Class' field as zero?
.br
Otherwise copy from IPv4 header's 'TOS'.
.IP --override-tos=BOOL
Override the IPv4 header's 'TOS' field as --tos?
.br
Otherwise copy from IPv6 header's 'Traffic Class'.
.IP --tos=INT
Value to override TOS as (only when --override-tos is ON)
.IP --mtu-plateaus=INT[,INT]*
Set the list of plateaus for ICMPv4 Fragmentation Neededs with MTU unset.
.IP --maximum-simultaneous-opens=INT
Set the maximum allowable 'simultaneous' Simultaneos Opens of TCP connections.
.IP --source-icmpv6-errors-better=BOOL
Translate source addresses directly on 4-to-6 ICMP errors?
.IP --handle-rst-during-fin-rcv=BOOL
Use transitory timer when RST is received during the V6 FIN RCV or V4 FIN RCV states?
.IP --f-args=INT
Defines the arguments that will be sent to F().
.br
(F() is defined by algorithm 3 of RFC 6056.)
.br
- First (leftmost) bit is source address.
.br
- Second bit is source port.
.br
- Third bit is destination address.
.br
- Fourth (rightmost) bit is destination port.
.IP --logging-bib=BOOL
Log BIBs as they are created and destroyed?
.IP --logging-session=BOOL
Log sessions as they are created and destroyed?
.IP --address-dependent-filtering=BOOL
Use Address-Dependent Filtering?
.br
ON is (address)-restricted-cone NAT, OFF is full-cone NAT.
.IP --drop-icmpv6-info=BOOL
Filter ICMPv6 Informational packets?
.IP --drop-externally-initiated-tcp=BOOL
Drop externally initiated TCP connections?
.IP --udp-timeout=INT
Set the UDP session lifetime (in seconds).
.IP --tcp-est-timeout=INT
Set the TCP established session lifetime (in seconds).
.IP --tcp-trans-timeout=INT
Set the TCP transitory session lifetime (in seconds).
.IP --icmp-timeout=INT
Set the ICMP session lifetime (in seconds).
.IP --fragment-arrival-timeout=INT
Set the timeout for arrival of fragments.
.IP --ss-enabled=BOOL
Enable Session Synchronization?
.IP --ss-flush-asap=BOOL
Try to synchronize sessions as soon as possible?
.IP --ss-flush-deadline=NUM
Inactive milliseconds after which to force a session sync.
.IP --ss-capacity=NUM
Maximim number of queuable entries.
.IP --ss-max-payload=NUM
Maximum amount of bytes joold should send per packet.

.SH EXAMPLES
Print the IPv6 pool:
.br
	jool --pool6 --display
.br
Add prefix 2001:db8::/96 to the IPv6 pool:
.br
	jool --pool6 --add 2001:db8::/96
.br
Remove prefix 2001:db8::/96 from the IPv6 pool:
.br
	jool --pool6 --remove 2001:db8::/96
.P
Print the number of IPv4 addresses in the pool:
.br
	jool --pool4 --count
.br
Add address 192.0.2.10 to the IPv4 pool:
.br
	jool --pool4 --add 192.0.2.10
.br
Remove address 192.0.2.10 from the IPv4 pool:
.br
	jool --pool4 --remove 192.0.2.10
.P
Print the Binding Information Base (BIB):
.br
	jool --bib
.br
Add a binding to the BIB:
.br
	jool --bib --add 192.0.2.1#11 1::1#22
.br
Remove a binding from the BIB:
.br
	jool --bib --remove 192.0.2.1#11 1::1#22
.P
Print the session table:
.br
	jool --session
.P
Print the global configuration values:
.br
	jool
.br
Update some global configuration value:
.br
	jool --address-dependent-filtering ON

.SH NOTES
TRUE, FALSE, 1, 0, YES, NO, ON and OFF are all valid booleans. You can mix case too.

.SH EXIT STATUS
Zero on success, non-zero on failure.

.SH AUTHOR
NIC Mexico & ITESM

.SH REPORTING BUGS
Our issue tracker is https://github.com/NICMx/Jool/issues.
If you want to mail us instead, use jool@nic.mx.

.SH COPYRIGHT
Copyright 2016 NIC Mexico.
.br
License: GPLv3+ (GNU GPL version 3 or later)
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
https://www.jool.mx
.br
https://www.jool.mx/en/documentation.html

