#CC=cgcc

ccflags-y := -I$(src)/../../include $(JOOL_FLAGS) -Wfatal-errors

obj-m += jool_siit.o

jool_common += ../common/rfc6145/4to6.o
jool_common += ../common/rfc6145/6to4.o
jool_common += ../common/rfc6145/common.o
jool_common += ../common/rfc6145/core.o
jool_common += ../common/address.o
jool_common += ../common/types.o
jool_common += ../common/str_utils.o
jool_common += ../common/packet.o
jool_common += ../common/stats.o
jool_common += ../common/log_time.o
jool_common += ../common/icmp_wrapper.o
jool_common += ../common/ipv6_hdr_iterator.o
jool_common += ../common/pool6.o
jool_common += ../common/rfc6052.o
jool_common += ../common/rtrie.o
jool_common += ../common/nl_buffer.o
jool_common += ../common/rbtree.o
jool_common += ../common/config.o
#jool_common += ../common/nl_handler.o
jool_common += ../common/route.o
jool_common += ../common/send_packet.o
jool_common += ../common/core.o
jool_common += ../common/error_pool.o
jool_common += ../common/namespace.o
#jool_common += ../common/nl/nl_core.o
#jool_common += ../common/nl/nl_receiver.o

jool_siit += xlat.o
jool_siit += eam.o
jool_siit += handling_hairpinning.o
jool_siit += nf_hook.o
jool_siit += pool.o
jool_siit += blacklist4.o
jool_siit += rfc6791.o
jool_siit += impersonator.o
jool_siit += json_parser.o

jool_siit-objs += ${jool_common} ${jool_siit}
