#CC=cgcc

ccflags-y := -I$(src)/../../include $(JOOL_FLAGS)
#ccflags-y += -Wfatal-errors

obj-m += jool_siit.o

jool_common += ../../common/stateless/xlat.o
jool_common += ../../common/netlink/config.o

jool_common += ../common/rfc6145/4to6.o
jool_common += ../common/rfc6145/6to4.o
jool_common += ../common/rfc6145/common.o
jool_common += ../common/rfc6145/core.o
jool_common += ../common/address.o
jool_common += ../common/atomic_config.o
jool_common += ../common/types.o
jool_common += ../common/str_utils.o
jool_common += ../common/packet.o
jool_common += ../common/stats.o
jool_common += ../common/log_time.o
jool_common += ../common/icmp_wrapper.o
jool_common += ../common/rtrie.o
jool_common += ../common/ipv6_hdr_iterator.o
jool_common += ../common/pool6.o
jool_common += ../common/rfc6052.o
jool_common += ../common/translation_state.o
jool_common += ../common/rbtree.o
jool_common += ../common/config.o
jool_common += ../common/route_in.o
jool_common += ../common/route_out.o
jool_common += ../common/send_packet.o
jool_common += ../common/core.o
jool_common += ../common/error_pool.o
jool_common += ../common/wkmalloc.o
jool_common += ../common/xlator.o
jool_common += ../common/nl/atomic_config.o
jool_common += ../common/nl/nl_handler2.o
jool_common += ../common/nl/nl_core2.o
jool_common += ../common/nl/bib.o
jool_common += ../common/nl/pool.o
jool_common += ../common/nl/eam.o
jool_common += ../common/nl/global.o
jool_common += ../common/nl/instance.o
jool_common += ../common/nl/joold.o
jool_common += ../common/nl/logtime.o
jool_common += ../common/nl/nl_common.o
jool_common += ../common/nl/pool4.o
jool_common += ../common/nl/pool6.o
jool_common += ../common/nl/session.o


jool_siit += eam.o
jool_siit += handling_hairpinning.o
jool_siit += nf_hook.o
jool_siit += pool.o
jool_siit += blacklist4.o
jool_siit += rfc6791.o
jool_siit += impersonator.o
jool_siit += rfc6791v6.o

jool_siit-objs += ${jool_common} ${jool_siit}
