ccflags-y := -I$(src)/../include -I$(src)/../../../include
EXTRA_CFLAGS += -DDEBUG

obj-m += graybox.o

graybox-objs += nf_hook.o
graybox-objs += config.o
graybox-objs += device_name.o
graybox-objs += receiver.o
graybox-objs += skb_ops.o
graybox-objs += send_packet.o
graybox-objs += ../../../mod/common/ipv6_hdr_iterator.o