ccflags-y := -I$(src)/../common -I$(src)/../../../include
EXTRA_CFLAGS += -DDEBUG

obj-m += graybox.o

graybox-objs += nf_hook.o
graybox-objs += expecter.o
graybox-objs += genetlink.o
graybox-objs += sender.o
graybox-objs += nl_handler.o
graybox-objs += ../common/types.o
graybox-objs += ../../../mod/common/error_pool.o
graybox-objs += ../../../mod/common/ipv6_hdr_iterator.o
graybox-objs += ../../../mod/common/route_out.o
