ccflags-y += -I$(src)/../common
ccflags-y += -I$(src)/common
ccflags-y += -I$(src)
ccflags-y += $(JOOL_FLAGS)
#ccflags-y += -Wfatal-errors

#CC=cgcc
#ccflags-y += -DCONFIG_SPARSE_RCU_POINTER

obj-m += jool.o

jool-objs += initialization.o

#jool-objs += ../common/nl-protocol.o

jool-objs += common/address.o
#jool-objs += common/atomic-config.o
jool-objs += common/config.o
jool-objs += common/core.o
#jool-objs += common/error-pool.o
jool-objs += common/handling-hairpinning.o
jool-objs += common/icmp-wrapper.o
jool-objs += common/ipv6-hdr-iterator.o
jool-objs += common/module-stats.o
jool-objs += common/module-types.o
jool-objs += common/packet.o
jool-objs += common/packet-init.o
jool-objs += common/rfc6052.o
jool-objs += common/rbtree.o
jool-objs += common/rtrie.o
jool-objs += common/send-packet.o
jool-objs += common/str-utils.o
jool-objs += common/wkmalloc.o
jool-objs += common/xlat.o
jool-objs += common/xlation.o
jool-objs += common/xlator.o

#jool-objs += common/nl/nl-atomic-config.o
#jool-objs += common/nl/nl-bib.o
#jool-objs += common/nl/nl-common.o
#jool-objs += common/nl/nl-core.o
#jool-objs += common/nl/nl-eam.o
#jool-objs += common/nl/nl-global.o
#jool-objs += common/nl/nl-handler.o
#jool-objs += common/nl/nl-instance.o
#jool-objs += common/nl/nl-joold.o
#jool-objs += common/nl/nl-logtime.o
#jool-objs += common/nl/nl-pool.o
#jool-objs += common/nl/nl-pool4.o
#jool-objs += common/nl/nl-pool6.o
#jool-objs += common/nl/nl-session.o

jool-objs += common/rfc7915/4to6.o
jool-objs += common/rfc7915/6to4.o
jool-objs += common/rfc7915/common.o
jool-objs += common/rfc7915/core.o

jool-objs += siit/eam.o
jool-objs += siit/rfc6791.o

jool-objs += nat64/compute-outgoing-tuple.o
jool-objs += nat64/determine-incoming-tuple.o
jool-objs += nat64/filtering-and-updating.o
jool-objs += nat64/joold2.o
jool-objs += nat64/timer.o

jool-objs += nat64/bib/db.o
jool-objs += nat64/bib/entry.o
jool-objs += nat64/bib/pkt-queue.o

jool-objs += nat64/pool4/db.o
jool-objs += nat64/pool4/rfc6056.o
