ccflags-y := -I$(src)/../include
#EXTRA_CFLAGS += -DDEBUG

obj-m += nat64.o

nat64-objs += types.o
nat64-objs += str_utils.o
nat64-objs += ipv6_hdr_iterator.o
nat64-objs += rfc6052.o
nat64-objs += out_stream.o
nat64-objs += pool6.o
nat64-objs += pool4.o
nat64-objs += bib.o
nat64-objs += session.o
nat64-objs += static_routes.o
nat64-objs += config.o
nat64-objs += config_validation.o
nat64-objs += config_proto.o
nat64-objs += determine_incoming_tuple.o
nat64-objs += filtering_and_updating.o
nat64-objs += compute_outgoing_tuple.o
nat64-objs += translate_packet.o
nat64-objs += handling_hairpinning.o
nat64-objs += send_packet.o
nat64-objs += xt_core.o
