.\" Manpage for jool's userspace app.
.\" Report bugs to jool@nic.mx.

.TH jool_siit 8 2017-07-25 v3.5.4 "SIIT Jool's Userspace Application"

.SH NAME
jool_siit - Interact with SIIT Jool (the kernel module).

.SH DESCRIPTION
Sends commands and requests to SIIT Jool.
.br
SIIT Jool is a kernel module you load into a Linux kernel. It implements RFC 6145.

.SH AVAILABILITY
Linux is the only OS in which this program makes sense.
.br
Kernels 3.2.0 and up.

.SH SYNTAX
jool_siit --instance (
.br
	[--add]
.br
	| --remove
.br
)
.P
jool_siit --pool6 (
.br
	[--display] [--csv]
.br
	| --count
.br
.RI "	| --add " <IPv6-prefix> " [--force]"
.br
.RI "	| --remove " <IPv6-prefix>
.br
.RI "	| --flush"
.br
)
.P
jool_siit --blacklist (
.br
	[--display] [--csv]
.br
	| --count
.br
.RI "	| --add " <IPv4-prefix>
.br
.RI "	| --remove " <IPv4-prefix>
.br
	| --flush
.br
)
.P
jool_siit --pool6791 (
.br
	[--display] [--csv]
.br
	| --count
.br
.RI "	| --add " <IPv4-prefix>
.br
.RI "	| --remove " <IPv4-prefix>
.br
	| --flush
.br
)
.P
.RI "jool_siit --eamt (
.br
	[--display] [--csv]
.br
	| --count
.br
.RI "	| --add " "<IPv4-prefix> <IPv6-prefix>" " [--force]"
.br
.RI "	| --remove " "<IPv4-prefix> <IPv6-prefix>"
.br
	| --flush
.br
)
.P
.RI "jool_siit [--global] (
.br
	[--display] [--csv]
.br
.RI "	| [--update] " FLAG_KEY = FLAG_VALUE
.br
)
.P
.RI "jool_siit [--file] (
.br
	/path/to/json/file
.br
)


.SH OPTIONS
.SS Operations
.IP --display
Print the table as output.
.IP --count
Count and print the number of entries in the table.
.IP --add
Create a new row using the rest of the arguments.
.IP --update
Change a configuration value based on the rest of the arguments.
.IP --remove
Delete the row described by the rest of the arguments.
.IP --flush
Empty the table.

.SS Others
.IP <IPv6-prefix>
.RI "IPv6 prefix to add to or remove from Jool's IPv6 pool or EAM table.
.br
.RI "The format is " IPV6_ADDRESS "[/" PREFIX_LENGTH "]."
.br
.RI "PREFIX_LENGTH defaults to 128."
.br
Exampĺe: 64:ff9b::/96
.IP <IPv4-prefix>
.RI "IPv4 addresses to add to or remove from the pool or EAM table."
.br
.RI "The format is " IPV4_ADDRESS "[/" PREFIX_LENGTH "]."
.br
.RI "PREFIX_LENGTH defaults to 32."
.br
Exampĺe: 1.2.3.4/30 (Means 1.2.3.4, 1.2.3.5, 1.2.3.6 and 1.2.3.7)
.IP --csv
Output the table in Comma/Character-Separated Values (.csv) format.

.SS "--global's FLAG_KEYs"
.IP --disable
Pause translation of packets.
.IP --enable
Resume translation of packets.
.IP --zeroize-traffic-class=BOOL
Always set the IPv6 header's 'Traffic Class' field as zero?
.br
Otherwise copy from IPv4 header's 'TOS'.
.IP --override-tos=BOOL
Override the IPv4 header's 'TOS' field as --tos?
.br
Otherwise copy from IPv6 header's 'Traffic Class'.
.IP --tos=INT
Value to override TOS as (only when --override-tos is ON).
.IP --mtu-plateaus=INT[,INT]*
Set the list of plateaus for ICMPv4 Fragmentation Neededs with MTU unset.
.IP --amend-udp-checksum-zero=BOOL
Compute the UDP checksum of IPv4-UDP packets whose value is zero?
.br
Otherwise drop the packet.
.IP --eam-hairpin-mode=NUM
Defines how EAM+hairpinning is handled.
.br
(0 = Disabled; 1 = Simple; 2 = Intrinsic)
.IP --randomize-rfc6791-addresses=BOOL
Randomize selection of address from the RFC6791 pool?
.br
Otherwise choose the 'Hop Limit'th address.
.IP --rfc6791v6-prefix=(ADDR6/NUM|null)
IPv6 prefix to generate RFC6791v6 addresses from.
.br
Use null to clear.

.SH EXAMPLES
Print the IPv6 pool:
.br
	jool_siit --pool6 --display
.br
Add prefix 2001:db8/96 to the IPv6 pool:
.br
	jool_siit --pool6 --add 2001:db8::/96
.br
Remove prefix 2001:db8/96 from the IPv6 pool:
.br
	jool_siit --pool6 --remove 2001:db8::/96
.P
Print the number of blacklisted addresses:
.br
	jool_siit --blacklist --count
.br
Blacklist prefix 192.0.2.0/24:
.br
	jool_siit --blacklist --add 192.0.2.0/24
.br
Allow translation of 192.0.2.0/24:
.br
	jool_siit --blacklist --remove 192.0.2.0/24
.P
.P
Print the RFC 6791 pool:
.br
	jool_siit --pool6791 --display
.br
Translate unknown router addresses as anything from 192.0.2.0/24:
.br
	jool_siit --pool6791 --add 192.0.2.0/24
.br
Revert the previous command:
.br
	jool_siit --pool6791 --remove 192.0.2.0/24
.P
Print the Explicit Address Mappings Table (EAMT):
.br
	jool_siit --eamt
.br
Add an entry to the EAMT:
.br
	jool_siit --eamt --add 2001:db8::/120 192.0.2.0/24
.br
Remove an entry from the EAMT:
.br
	jool_siit --eamt --remove 2001:db8::/120 192.0.2.0/24
.P
Print the global configuration values:
.br
	jool_siit
.br
Update some global configuration value:
.br
	jool_siit --zeroize-traffic-class ON

.SH NOTES
TRUE, FALSE, 1, 0, YES, NO, ON and OFF are all valid booleans. You can mix case too.

.SH EXIT STATUS
Zero on success, non-zero on failure.

.SH AUTHOR
NIC Mexico & ITESM

.SH REPORTING BUGS
Our issue tracker is https://github.com/NICMx/Jool/issues.
If you want to mail us instead, use jool@nic.mx.

.SH COPYRIGHT
Copyright 2016 NIC Mexico.
.br
License: GPLv3+ (GNU GPL version 3 or later)
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
https://www.jool.mx
.br
https://www.jool.mx/en/documentation.html

